### PR TITLE
Add CSV download action to LegalBasis in Django Admin

### PR DESCRIPTION
**Pull request by r4vi**
Make custom Model Admin that is able to export the model with it's nested
consent types in a single row

### CODE REVIEW

**Comment by r4vi** [comment]
code climate will be happy once we merge the other PR

**Comment by kerin** [comment]
I'm not fully convinced that CodeClimate is all that useful anyway to be honest, given that we have broadly equivalent checks running in CircleCI, so we can remove it entirely if it proves to be annoying.

**Comment by r4vi** [comment]
leave it for now, I've made it roughly match our config so it shouldn't be too annoying from now on

**Comment by r4vi** [comment]
re-requesting review because of rebase

**Pull request merged**
